/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.69KB] > C:\Users\HP\Downloads\Portfolio images\portgas_d._ace_one_piece\scene-transformed.glb [310.71KB] (-8320%)
Author: Emm (Scenario) (https://sketchfab.com/edemaistre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/portgas-d-ace-one-piece-c560562fea844b98b797915b07c8ba90
Title: Portgas D. Ace (One Piece)
*/

"use client";
import React, { useRef } from 'react'
import { useGLTF, Center, OrbitControls } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const Ace = React.memo(function Ace(props) {
  const { nodes, materials } = useGLTF('/models/Ace.glb')

  const modelRef = useRef();

  useFrame((state) => {
    // Floating animation
    modelRef.current.position.y =
      0 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <>
      <OrbitControls enableZoom={false} enablePan={false} />
      <group {...props} dispose={null} ref={modelRef} position={[0, 1.5, 0]}>
        {/* Try a relatively generic scale of 3; the user can tweak it! */}
        <group scale={[20, 20, 20]} rotation={[0, -Math.PI / 2.5, 0]}>
          <Center>
            <mesh geometry={nodes.Object_2.geometry} material={materials.material_1} rotation={[-Math.PI / 2, 1.56, 0]} />
          </Center>
        </group>
      </group>
    </>
  )
});

export default Ace;

useGLTF.preload('/models/Ace.glb');
