/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [19.76KB] > C:\Users\HP\Downloads\Portfolio images\zoro_katana\scene-transformed.glb [2.2MB] (-11010%)
Author: kaiyi97 (https://sketchfab.com/kaiyi97)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/zoro-katana-42d8173aed6f4400bbaf006ae506ec68
Title: Zoro Katana_黒刀秋水
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF, Center } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const Katana = React.memo(function Katana(props) {
  const modelRef = useRef()

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.007
    }
  })

  const { nodes, materials } = useGLTF('/models/katana.glb')
  return (
    <group {...props} dispose={null}>
      {/* Shift position without affecting rotation pivot */}
      <group position={[0.5, 0, 0]}>
        <group ref={modelRef}>
          <group scale={[4, 4, 4]} rotation={[Math.PI / 2, 0, 0]}>
            <Center>
              <mesh geometry={nodes['������002_������_0'].geometry} material={materials.material} position={[-19.259, 17.646, -1.451]} rotation={[-0.011, 0.025, 0.709]} scale={0.015} />
              <mesh geometry={nodes['������1_������2_0'].geometry} material={materials.material_1} position={[-19.079, 17.662, -1.865]} rotation={[0.056, -0.139, 0.92]} scale={0.015} />
              <mesh geometry={nodes['������1_������_0'].geometry} material={materials.material_2} position={[-19.079, 17.662, -1.865]} rotation={[0.056, -0.139, 0.92]} scale={0.015} />
              <mesh geometry={nodes['������002_������_0_1'].geometry} material={materials.material_3} position={[-19.26, 17.647, -1.47]} rotation={[-0.011, 0.025, -0.469]} scale={[0.019, 0.019, 0.015]} />
              <mesh geometry={nodes['������002_������_0_2'].geometry} material={materials.material_4} position={[-19.271, 17.642, -1.879]} rotation={[-0.011, 0.025, 0.709]} scale={[0.01, 0.015, 0.015]} />
              <mesh geometry={nodes['������002_������2_0'].geometry} material={materials.material_5} position={[-19.271, 17.642, -1.879]} rotation={[-0.011, 0.025, 0.709]} scale={[0.01, 0.015, 0.015]} />
            </Center>
          </group>
        </group>
      </group>
    </group>
  )
})

export default Katana;

useGLTF.preload('/models/katana.glb')
