/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [5.89KB] > C:\Users\HP\Downloads\Portfolio images\luffy_hat\scene-transformed.glb [95.36KB] (-1519%)
Author: ผมเรียนกราฟิก (https://sketchfab.com/ramakienx)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/luffy-hat-3af7f978b35b49d1a51bf1f3aba90923
Title: Luffy Hat
*/

"use client";
import React, { useRef } from 'react'
import { useGLTF, Center } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const StrawHat = React.memo(function StrawHat(props) {
  const { nodes, materials } = useGLTF('/models/Straw-hat.glb')

  const modelRef = useRef();

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.007;
    }
  });

  return (
    <group {...props} dispose={null} ref={modelRef} position={[0, 0, 0]}>
      {/* Starting with a generic scale, easily tweakable */}
      <group scale={[2, 2, 2]} rotation={[0, 0, 0]}>
        <Center>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.line} />
        </Center>
      </group>
    </group>
  )
});

export default StrawHat;

useGLTF.preload('/models/Straw-hat.glb');
